platform :ios, '7.0'

pod 'AFNetworking', '~> 2.4.1'
pod 'SSKeychain', '~> 1.2.2'
pod 'SVProgressHUD', '~> 1.0'

target :HumonTests  do
  pod 'Kiwi', '~> 2.3.0'
  pod 'OHHTTPStubs', '~> 3.0.2'
end

target :HumonUITests, :exclusive => true do
  pod 'KIF', '~> 3.0.8'
end
