platform :ios, '8.0'

target 'Humon' do
  pod 'SSKeychain', '~> 1.2.2'
  pod 'SVProgressHUD', '~> 1.0'
  pod 'AFNetworking', '~> 2.4.1'

  target 'HumonTests' do
    inherit! :search_paths
    pod 'Kiwi', '~> 2.3.0'
    pod 'OHHTTPStubs', '~> 3.0.2'
  end
end
